### ISSUE TITLE
Anyone still working on this?

### ISSUE THREAD

**Issue by JohnSmith-LT** [LLK/scratch-html5#103]
Hi,

I've just this minute forked the project and run compare.html and the flash version loads fine but the html5 version hangs at loading project:

![image](https://cloud.githubusercontent.com/assets/3907362/6873032/3e382bc6-d4a5-11e4-9136-59188bf4a45b.png)

Now, looking at issues and pull requests, I see that nothing has been done for months...

My question is, am I doing something very silly or is the current master broken and is anyone actually still working on this? I'd love to be involved but don't know if I want to donate my time to getting some stuff done if it's going nowhere...

**Comment by JohnSmith-LT** [comment]
Getting a few errors after rolling back a few commits to the Merge of the pull request from ScottLogic/sprite-sprite-collisions

SWF Error: Calling JSeditorReady() failed.
VM1982:1 SWF v433a   compare.html:49 
Uncaught Error: Error: An invalid exception was thrown.    compare.html:49
(anonymous function)  jquery.min.js:3
f.event.dispatch    jquery.min.js:3
f.event.add.h.handle.i

so something isn't right, probably at my end...

Any ideas?

**Comment by JohnSmith-LT** [comment]
So I solved the problem, well traced it, in case anyone is remotely interested...

The problem is that .load in the Sprite.js object doesnt fire for one of the sprites - it seems to take slightly longer to attach the event meaning the resource loads from the cache before .load event is attached and thus never fires.

Gonna rewrite Sprite to use new jquery best practice for loading images, ensuring that load always fires.

**Comment by rmdobservations** [comment]
I am interested in the progress of scratch-html5. I am a relative newcomer to how github functions (I can clone projects but that's about it).
I have been learning javascript (jquery included) and am willing to do some testing and maybe contribute somehow. My motivation is based on a children's activity where we use Scratch on Linux-mint laptops and am therefore interested in avoiding the use of Flash. 
Rose

**Comment by MarcSchober** [comment]
It seems that the Server is sending the wrong content type in the header:
https://code.google.com/p/chromium/issues/detail?id=482617
